export const studentsdb = [
    { id: 1, name: "Arun", age: 20, dept: "CSE", cgpa: 8.7 },
    { id: 2, name: "Priya", age: 21, dept: "ECE", cgpa: 9.1 },
    { id: 3, name: "Rahul", age: 19, dept: "IT", cgpa: 8.4 },
    { id: 4, name: "Sneha", age: 22, dept: "AI", cgpa: 9.3 },
    { id: 5, name: "Vikram", age: 20, dept: "CSE", cgpa: 8.9 },
    { id: 6, name: "Ananya", age: 21, dept: "AIML", cgpa: 9.5 },
    { id: 7, name: "Karthik", age: 20, dept: "MECH", cgpa: 7.8 },
    { id: 8, name: "Divya", age: 19, dept: "CSE", cgpa: 8.6 },
    { id: 9, name: "Rohan", age: 22, dept: "ECE", cgpa: 8.2 },
    { id: 10, name: "Meena", age: 20, dept: "IT", cgpa: 9.0 },
    { id: 11, name: "Aditya", age: 21, dept: "AI", cgpa: 8.8 },
    { id: 12, name: "Keerthana", age: 20, dept: "CSE", cgpa: 9.2 },
    { id: 13, name: "Sanjay", age: 22, dept: "ECE", cgpa: 7.9 },
    { id: 14, name: "Harini", age: 19, dept: "AIML", cgpa: 9.4 },
    { id: 15, name: "Manoj", age: 21, dept: "IT", cgpa: 8.1 },
    { id: 16, name: "Aishwarya", age: 20, dept: "CSE", cgpa: 9.0 },
    { id: 17, name: "Naveen", age: 22, dept: "MECH", cgpa: 7.6 },
    { id: 18, name: "Swetha", age: 21, dept: "AI", cgpa: 9.1 },
    { id: 19, name: "Vishal", age: 20, dept: "ECE", cgpa: 8.5 },
    { id: 20, name: "Pooja", age: 19, dept: "CSE", cgpa: 8.8 },
    { id: 21, name: "Suresh", age: 21, dept: "IT", cgpa: 7.7 },
    { id: 22, name: "Lavanya", age: 20, dept: "AIML", cgpa: 9.6 },
    { id: 23, name: "Rakesh", age: 22, dept: "CSE", cgpa: 8.3 },
    { id: 24, name: "Nandhini", age: 21, dept: "ECE", cgpa: 9.0 },
    { id: 25, name: "Ajay", age: 20, dept: "AI", cgpa: 8.7 },
    { id: 26, name: "Shreya", age: 19, dept: "CSE", cgpa: 9.3 },
    { id: 27, name: "Dinesh", age: 22, dept: "IT", cgpa: 8.0 },
    { id: 28, name: "Madhavi", age: 21, dept: "MECH", cgpa: 7.9 },
    { id: 29, name: "Tarun", age: 20, dept: "AIML", cgpa: 9.2 },
    { id: 30, name: "Neha", age: 19, dept: "CSE", cgpa: 8.9 },
    { id: 31, name: "Surya", age: 21, dept: "ECE", cgpa: 8.6 },
    { id: 32, name: "Ishita", age: 20, dept: "AI", cgpa: 9.5 },
    { id: 33, name: "Aravind", age: 22, dept: "IT", cgpa: 8.2 },
    { id: 34, name: "Deepa", age: 21, dept: "CSE", cgpa: 9.1 },
    { id: 35, name: "Varun", age: 20, dept: "ECE", cgpa: 8.4 },
    { id: 36, name: "Nithya", age: 19, dept: "AIML", cgpa: 9.4 },
    { id: 37, name: "Praveen", age: 22, dept: "MECH", cgpa: 7.5 },
    { id: 38, name: "Kavya", age: 21, dept: "CSE", cgpa: 8.8 },
    { id: 39, name: "Akash", age: 20, dept: "IT", cgpa: 8.3 },
    { id: 40, name: "Riya", age: 19, dept: "AI", cgpa: 9.0 },
    { id: 41, name: "Mohan", age: 22, dept: "ECE", cgpa: 7.8 },
    { id: 42, name: "Sanjana", age: 20, dept: "CSE", cgpa: 9.2 },
    { id: 43, name: "Gokul", age: 21, dept: "AIML", cgpa: 8.7 },
    { id: 44, name: "Bhavana", age: 20, dept: "IT", cgpa: 9.1 },
    { id: 45, name: "Yash", age: 22, dept: "CSE", cgpa: 8.5 },
    { id: 46, name: "Ramya", age: 19, dept: "ECE", cgpa: 9.3 },
    { id: 47, name: "Ashwin", age: 21, dept: "AI", cgpa: 8.9 },
    { id: 48, name: "Monisha", age: 20, dept: "AIML", cgpa: 9.5 },
    { id: 49, name: "Ravi", age: 22, dept: "MECH", cgpa: 7.7 },
    { id: 50, name: "Pavithra", age: 21, dept: "CSE", cgpa: 9.0 }
];



